### PR TITLE
@types packages upgraded

### PR DESCRIPTION
**Pull request by M-ZubairAhmed**
### Issues
- https://github.com/ctco-dev/react-template/issues/25
- https://github.com/ctco-dev/react-template/issues/26

## Changes
1. Upgraded @types dev dependencies of `react` and `react-dom` to any latest version of ^16 (according sem versioning)
2. Upgraded  @types `material-ui` to latest ^0.18.2 version

### CODE REVIEW

**Comment by trioletas** [comment]
Thanks for contributing!
The TypeScript compiler is not happy: https://travis-ci.org/ctco-dev/react-template/builds/284185876#L510
could you please take a look in to this error? Appreciated!

**Comment by M-ZubairAhmed** [comment]
sure I will look into it

**Comment by M-ZubairAhmed** [comment]
### Question
may i know which node version it recommended to use in this in app.
### Test executed
i just ran the following commands and they came out clean
`npm start`
`npm build`
`npm test`
`npm start storybook`
`npm start build-storybook`
### result
image

### Node version
v8.3.0

**Comment by trioletas** [comment]
8+ is fine, could you please change the node version in https://github.com/ctco-dev/react-template/blob/master/.travis.yml to 8
Let's see if that helps.

**Comment by M-ZubairAhmed** [comment]
https://github.com/ctco-dev/react-template/issues/24
[@types/jes](https://www.npmjs.com/package/@types/jest)t is also updated in this PR

**Comment by aeldar** [comment]
Hello @M-ZubairAhmed.
Recently we updated this repository implementing a lot of changes. We changed approach to reuse [CRA](https://github.com/facebookincubator/create-react-app). Now we are using it without ejecting. The webpack configuration is patched with the help of [react-app-rewired](https://github.com/timarney/react-app-rewired) as we tend to reckon it is more perspective approach to use CRA.
We updated all dependencies in context of that last update.
This pull request is closing as not actual anymore. Sorry for that, and thank you for contributing.
If you are interested in the old ejected version of this repo, you can find it under [v1.0.14-ejected](https://github.com/ctco-dev/react-template/tree/v1.0.14-ejected) tag.

**Comment by M-ZubairAhmed** [comment]
sure please open up issues in the new implementation if any, i would love to contribute.

**Pull request closed without merging**
